name: On push sftp copy

on:
  push:
    branches: 
    - master
  workflow_dispatch:
  
jobs:
  copy_to_sftp:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: 1.studio.boardgamearena.com/${{ github.event.repository.name }}
        username: MrKywar
        password: ${{ secrets.SFTP_PASSWORD }}
        exclude: |
          **/.git*
          **/.git*/**
          README.md
