name: On push sftp copy

on:
  push:
    branches: 
    - master
  workflow_dispatch:
  
jobs:
  copy_to_sftp:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: sftp://1.studio.boardgamearena.com/${{ github.event.repository.name }}
        ftp-username: ${{ secrets.SFTP_USERNAME }}
        ftp-password: ${{ secrets.SFTP_PASSWORD }}
        git-ftp-args: --insecure
        exclude: |
          .git*
          .git*/**
          .vscode/**
          README.md
